### ISSUE TITLE
Any paper published about this project?

### ISSUE THREAD

**Issue by dionstew** [vincentmllr/deep-robot-grasping#3]
Hi, I am an university student. I have found that this project is interesting and I would to explore the simulation environment related to this project. I'd like to know if you have any published work about this project so I can take it as a reference on my assignments.

**Comment by vincentmllr** [comment]
Hi Dion, Thank you for your message and your interest in this project! The project was part of my bachelor thesis, but its wasn't published any further. I am not sure if that is enough to reference it. I will upload it in this repository anyways in the next days and let you know once it is online.
Best wishes,
Vincent

**Comment by dionstew** [comment]
That would be very great help, of course I will be looking forward to the paper.

**Comment by vincentmllr** [comment]
Hi Dion, I uploaded my bachelor thesis under https://github.com/vincentmllr/deep-robot-grasping/blob/master/AA-82179-10961-Vincent-M%C3%BCller-Schriftliche%20Ausarbeitung.pdf.
Unfortunately its only in German, but I hope it is still helpful to you.
Best wishes,
Vincent

**Comment by dionstew** [comment]
Hi Vincent. That's a big help, thank you.
It is fine. I have a friend who is good at German to translate it, so no problem.

Regards,
Dion
